### ISSUE TITLE
Restore Old Tweet Layout

### ISSUE THREAD

**Issue by maciclol** [Bl4Cc4t/GoodTwitter2#261]
Hi. I've been using this script for a bit, and I must say I'm a fan. However, there is one feature which would be nice to have added, which is the old post layout.

When Twitter implemented their new layout, the comment/like/retweet buttons changed slightly and the share button changed completely. It would be great to have the old ones back. You can take a look at the images below in case you're unsure of what I'm referring  to.

[Screenshot of a Tweet on the old layout](https://user-images.githubusercontent.com/67235929/111151938-6cad1780-8590-11eb-9a14-a3dc0bad8a0a.PNG)
[Screenshot of a Tweet on the current layout](https://user-images.githubusercontent.com/67235929/111151940-6d45ae00-8590-11eb-9f40-730734228447.PNG)

**Comment by Bl4Cc4t** [comment]
#### The share button
The share button used to be a letter icon because that was the only purpose it had, sharing the tweet via DM. It has multiple functions now, so it makes no sense to use the letter icon imo.

I won't change that, but you can use the following CSS with any style changing extension or if you're on Firefox with [`userContent.css`](https://superuser.com/questions/318912/how-can-i-override-the-css-of-a-site-in-firefox-with-usercontent-css):

```css
[data-testid=tweet] > div > div > [role=group] > :last-child svg g :first-child {
  display: none;
}
[data-testid=tweet] > div > div > [role=group] > :last-child svg g :last-child {
  d: path("M19.25 3.018H4.75C3.233 3.018 2 4.252 2 5.77v12.495c0 1.518 1.233 2.753 2.75 2.753h14.5c1.517 0 2.75-1.235 2.75-2.753V5.77c0-1.518-1.233-2.752-2.75-2.752zm-14.5 1.5h14.5c.69 0 1.25.56 1.25 1.25v.714l-8.05 5.367c-.273.18-.626.182-.9-.002L3.5 6.482v-.714c0-.69.56-1.25 1.25-1.25zm14.5 14.998H4.75c-.69 0-1.25-.56-1.25-1.25V8.24l7.24 4.83c.383.256.822.384 1.26.384.44 0 .877-.128 1.26-.383l7.24-4.83v10.022c0 .69-.56 1.25-1.25 1.25z");
}
```

#### The "more" button (top right)
You're actually wrong about that being changed with the new layout, they changed the caret somewhat recently. You can still see it in the [screenshots provided at the bottom of the readme](https://github.com/Bl4Cc4t/GoodTwitter2#previews).

I didn't notice that change and I will probably replace the dots with the old caret in the next update.

#### Conclusion
Thanks for your report and for spotting these changes!


Related issue: #26
