### ISSUE TITLE
White back buttons

### ISSUE THREAD

**Issue by Diyamund** [Bl4Cc4t/GoodTwitter2#330]
**Please check the following before you continue**
- [*] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [*] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [*] Checked if the issue has not been reported before

**Describe the bug**
Twitter's design update messaged up the back button color and turned it white.
```css
[class="r-jwli3a r-4qtqp9 r-yyyyoo r-1hjwoze r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-12ym1je"] {
    color: var(--color-user);
}
```
This CSS reverts it to the user color like before the update.
(I'm like 99% sure someone can make a better selector for this snippet)

**Screenshots**
Twitter Update:
![image](https://user-images.githubusercontent.com/44238627/129426288-fdfc87b0-3d23-4e9e-b722-ff82760407e5.png)
With CSS:
![image](https://user-images.githubusercontent.com/44238627/129426298-e4849bff-3089-4aae-851d-ad7ddd7e02dc.png)

**Your configuration**
 - Firefox Developer Edition 92.0b3
 - Tampermonkey 4.13.6136
