### ISSUE TITLE
Updating the Spanish translation

### ISSUE THREAD

**Issue by gaelcoral** [Bl4Cc4t/GoodTwitter2#503]
I noticed the Spanish translation has not been updated for a long time, so I took the task of correcting and adding the missing translations.

```
# spanish language file

# strings that are used on the site already.
twitter-default:
  composeNewTweet: Twittear
  contentWarningNudity: Desnudez
  contentWarningViolence: Violencia
  contentWarningSensitiveContent: Contenido delicado
  joinDate: Se unió en $date$
  navBookmarks: Guardados
  navCommunities: Comunidades
  navMessages: Mensajes
  navExplore: Explorar
  navHome: Inicio
  navLists: Listas
  navNotifications: Notificaciones
  navProfile: Perfil
  statsFollowers: Seguidores
  statsFollowing: Siguiendo
  statsLikes: Me gusta
  statsMoments: Momentos
  statsTweets: Tweets
  topics: Temas
  translateTweet: Traducir Tweet
  users: Usuarios

# strings that are used on various parts within the script.
script:
  bornDate: "Fecha de nacimiento: $date$"
  bornYear: "Fecha de nacimiento: $year$"
  favorite: Favorito
  favorites: Favoritos
  followedBy0: Ninguno de tus seguidores te sigue
  followedBy1: Seguido por $p1$
  followedBy2: Seguido por $p1$ y $p2$
  followedBy3: Seguido por $p1$, $p2$ y $p3$
  followedBy4Plus: Seguido por $p1$, $p2$ y otros $nr$ a quienes tú sigues
  translatedTweetInfo: Traducido del $lang$ por $source$
  qbBlock: Bloquear
  qbBlocked: Bloqueado
  qbUnblock: Desbloquear
  updatedInfo: ¡Se actualizó a $version$!
  updatedInfoChangelog: Lista de cambios

# these strings are for the gt2 settings page.
settings:
  headers:
    settingsHeaderTimeline: Cronología
    settingsHeaderSidebars: Barras laterales
    settingsHeaderGlobalLook: Apariencia general
    settingsHeaderOther: Otros

  timeline:
    forceLatest: Forzar "Tweets más recientes"
    forceLatestDesc: Al activar el modo "Tweets más recientes" no se mantiene de forma permanente. Tras activar este ajuste, la página habilitará automáticamente el modo de "Tweets más recientes".
    biggerPreviews: Previsualizaciones de imágenes más grandes
    biggerPreviewsDesc: Las imágenes más largas de algunos tweets se muestran en toda su longitud.

  tweets:
    hideTranslateTweetButton: Ocultar botón de Traducir Tweet
    tweetIconsPullLeft: Agrupar los botones de interacción de los tweets a la izquierda
    hidePromoteTweetButton: Ocultar el botón "Promocionar Tweet"
    showMediaWithContentWarnings: Mostrar siempre los contenidos con advertencia
  sidebars:
    stickySidebars: Fijar las barras laterales
    smallSidebars: Hacer las barras laterales pequeñas
    smallSidebarsDesc: Las barras laterales será 290px en lugar de 350px de ancho.
    hideTrends: Ocultar Tendencias
    leftTrends: Barra lateral de Tendencias hacia la izquierda
    leftTrendsDesc: Muestra las tendencias de la barra lateral hacia la izquierda.
    show5Trends: Mostrar siempre 5 Tendencias

  profile:
    legacyProfile: Diseño Clásico de Perfil
    squareAvatars: Avatares Cuadrados
    disableHexagonAvatars: Desactivar los avatares hexagonales
    enableQuickBlock: Habilitar el bloqueo rápido
    enableQuickBlockDesc: Pasa el ratón por encima del botón de seguir durante 3 segundos para bloquear un perfil.
    leftMedia: Hacer las barras laterales de contenido multimedia hacia la izquierda 
    leftMediaDesc: Muestra el contenido multimedia de los perfiles de la barra lateral hacia la izquierda.
    profileMediaRedirect: Redirigir a /media al visitar las páginas de los perfiles.

  global-look:
    hideFollowSuggestions: Ocultar "A quién seguir"
    hideFollowSuggestionsBox: Ocultar $type$ de $location$
    fontOverride: Utilizar una fuente personalizada
    fontOverrideDesc: Establece una fuente personalizada para sustituir la fuente predeterminada. Esto sólo funciona si tienes instalada una fuente.
    colorOverride: Utilizar un color personalizado
    colorOverrideDesc: Establece un color personalizado para sustituir el predeterminado.
    hideMessageBox: Ocultar la bandeja de mensajes
    hideMessageBoxDesc: Oculta la nueva bandeja de mensajes que encuentra presente en la esquina inferior de la derecha.
    rosettaIcons: Iconos de Rosetta
    rosettaIconsDesc: Utiliza la fuente de iconos "Rosetta" previo a 2017
    favoriteLikes: Reemplazar los "Me gusta" por "Favoritos" (por ahora solamente iconos)

  other:
    updateNotifications: Notificaciones de actualización de GoodTwitter 2
    expandTcoShortlinks: Expandir enlaces abreviados de t.co
    mobileRedirect: Redirigir las URL para móviles 
```
